services:
  db:
    container_name: postgres_mini_app
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tg_mini_app

  redis:
    container_name: redis_mini_app
    image: redis:6.2
    restart: always
    ports:
      - 6380:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - tg_mini_app

volumes:
  postgres_data:
  redis_data:

networks:
  tg_mini_app: